[package]
name = "tengwar_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "tengwar_wrapper"
crate-type = ["staticlib"]


[build-dependencies]
cbindgen = "0.26.0"

[dependencies]
tengwar = "1.1.0"
